const C = {
  en: {
    // Hero
    heroBadge: "paper Records Management",
    heroTitle: "Take complete control of your paper documents",
    heroSub: "Enterprise paper Records & Warehouse Management",
    // heroPain: "Lost files. Slow retrievals. No proof of custody. Rising warehouse costs.",
    heroDesc:"DocuArena is a purpose-built paper Records Management (PRM) platform that gives your organization complete visibility and control over every paper record—from receiving to secure destruction.",
    // heroDesc2:
      // "Built specifically for organizations managing paper archives, DocuArena transforms manual warehouse operations into intelligent, barcode-driven workflows that improve operational efficiency, strengthen compliance, and reduce costs.",
    heroCta: "Book a Live Demo",
    heroCtaAlt: "Calculate Your Savings",
    // Enterprise Ready
    readyTitle: "Enterprise Ready",
    ready: [
      "Barcode-Verified Chain of Custody",
      "Complete Audit Trail",
      "Role-Based Security",
      "Multi-Language (English • العربية • Français)",
      "REST API Integration",
      "Enterprise Scalability",
      "Secure paper Records Lifecycle Management",
    ],
    // Challenges
    // challengesKicker: "The Reality of Manual Records Management",
    challengesTitle: "Are These Challenges Familiar?",
    challengesSub: "Managing paper records shouldn't mean managing uncertainty.",
    challenges: [
      "Files disappear and nobody knows where they went.",
      "Retrieval requests take hours — or even days.",
      "Audits become stressful because records cannot be fully traced.",
      "Warehouse space continues to grow without visibility.",
      "Manual spreadsheets create errors and duplicate work.",
      "Records move without documented proof of custody.",
      "Teams operate in disconnected systems.",
      "Management lacks real-time operational visibility.",
    ],
    challengesClose: "If any of these sound familiar, you're not alone. They're exactly the challenges DocuArena was built to solve.",
    // paper records still matter
    // matterKicker: "Why paper Records Still Matter",
    matterTitle: "paper Records Still Matter",
    matterP1:
      "Digital transformation has changed how organizations manage information — but it has not eliminated paper records.",
    matterP2:
      "Original contracts, legal files, financial records, healthcare documents, engineering drawings, and government archives still require secure paper storage and controlled handling.",
    matterP3:
      "Yet many organizations continue managing these critical assets using spreadsheets, paper logs, and manual processes. The result is predictable:",
    matter: [
      "Lost files",
      "Slow retrieval",
      "Compliance exposure",
      "Operational inefficiency",
      "Rising warehouse costs",
      "Limited visibility",
    ],
    matterClose: "DocuArena was specifically built to solve these challenges through intelligent, barcode-based paper document management.",
    // One platform
    // platformKicker: "One Platform.",
    platformTitle: "One Platform",
    platform: [
      { q: "Can't find a file?", a: "Advanced Search locates any box, file, or document in seconds." },
      { q: "Retrieval requests buried in emails?", a: "Automated Work Orders manage the complete request lifecycle — from approval to delivery." },
      { q: "No visibility into warehouse operations?", a: "Live warehouse monitoring gives you complete control over storage locations, occupancy, and movement." },
      { q: "Records leaving without accountability?", a: "Every movement is verified through barcode scanning, creating a complete digital chain of custody." },
      { q: "Teams working across multiple locations?", a: "The mobile application keeps warehouse operators, drivers, and field teams connected in real time." },
      // { q: "Retention deadlines approaching?", a: "Automated retention schedules and destruction alerts ensure records are managed according to policy." },
      { q: "Operational issues discovered too late?", a: "Exception Management identifies problems before they become SLA violations." },
      { q: "Leadership lacks operational insight?", a: "Executive dashboards provide live KPIs, warehouse utilization, operational performance, and customer activity." },
      { q: "Existing DMS or ERP already in place?", a: "DocuArena integrates seamlessly with your existing business systems through REST APIs — without disrupting your current technology investments." },
    ],
    platformClose: "One enterprise platform. Complete operational control.",
    // Lifecycle
    // lifecycleKicker: "The Document Lifecycle",
    lifecycleTitle: "From Receiving to Secure Destruction",
    lifecycleSub: "Every paper record follows a fully controlled lifecycle.",
    lifecycle: [
      { title: "Receiving", desc: "Records are received, registered, and validated." },
      { title: "Barcode Assignment", desc: "Every box, file, and document receives a unique identity." },
      { title: "Storage", desc: "Records are intelligently assigned to optimized warehouse locations." },
      { title: "Request Management", desc: "Authorized users submit retrieval and service requests." },
      { title: "Retrieval & Delivery", desc: "Warehouse and transportation teams execute barcode-verified work orders." },
      { title: "Return", desc: "Returned records are scanned and restored to their storage locations automatically." },
      { title: "Retention Management", desc: "Retention schedules are monitored with automated notifications." },
      { title: "Secure Destruction", desc: "Expired records are destroyed through controlled, documented, and fully auditable processes." },
    ],
    // Features
    // featuresKicker: "Platform Capabilities",
    featuresTitle: "Everything You Need in One Enterprise Platform",
    featuresSub: "Powerful, purpose-built modules that work together as one unified system.",
    features: [
      { title: "Intelligent Warehouse Management", desc: "Manage warehouses, storage structures, media types, and warehouse capacity from one centralized platform." },
      { title: "Barcode Management", desc: "Generate, print, and reprint barcodes for warehouses, locations, boxes, files, and documents." },
      { title: "Advanced Search", desc: "Locate records instantly using barcodes, descriptions, metadata, departments, customers, dates, or custom criteria." },
      { title: "Work Order Management", desc: "Automate retrievals, returns, transportation, destruction requests, and internal warehouse services." },
      { title: "Mobile Operations", desc: "Enable warehouse operators to execute work orders and barcode scans anywhere using handheld devices." },
      { title: "Fleet Management", desc: "Coordinate vehicles, drivers, couriers, and deliveries with complete operational visibility." },
      { title: "Retention Management", desc: "Manage legal retention schedules, review dates, and secure destruction workflows automatically." },
      { title: "Exception Management", desc: "Monitor operational issues and SLA exceptions before they affect customer service." },
      { title: "Executive Dashboards & Reporting", desc: "Measure warehouse utilization, customer activity, operational KPIs, productivity, and service performance through real-time dashboards." },
      { title: "Enterprise Administration", desc: "Manage users, roles, permissions, departments, customers, contracts, and business rules from one secure administration console." },
    ],
    // Mobile
    mobileHeroTitle: "DocuArena Mobile",
    mobileHeroSub: "Every Operation in Your Pocket",
    mobileHeroDesc:
      "Warehouse staff and field teams stay connected to the central platform from anywhere. Scan, execute, verify, and update paper records in real time — no paperwork, no delays.",
    // mobileKicker: "Operations Anywhere",
    mobileTitle: "Operations Anywhere",
    mobileSub: "Warehouse operations should never stop because your team leaves the office, DocuArena Mobile Application enables warehouse staff of performing all the duties wherever and whenever they are, every action remains visible and registered.",
    mobileDesc: "The DocuArena Mobile Application enables warehouse staff and field teams to:",
    mobile: [
      "Scan barcodes instantly",
      "Execute work orders",
      "Update record status in real time",
      "Verify deliveries and returns",
      "Capture warehouse activities",
      "Synchronize every operation with the central platform",
    ],
    mobileClose: "Whether inside the warehouse or at a customer location, every movement remains visible and fully controlled.",
    mobileCta: "Explore the Mobile Experience",
    // Cost calculator
    // costKicker: "The Hidden Cost of Manual Processes",
    costTitle: "What Are Manual Processes Costing You?",
    costSub:
      "Every delayed retrieval. Every misplaced file. Every unnecessary warehouse visit. Every manual spreadsheet. Every compliance issue. They all have a measurable cost.",
    costDesc: "Use our interactive paper Records Management Cost Calculator to discover:",
    cost: [
      "Current operational costs",
      "Warehouse efficiency",
      "Labor utilization",
      "Retrieval performance",
      "Potential annual savings",
      "Expected Return on Investment (ROI)",
      "Estimated payback period",
    ],
    costCta: "Calculate Your Savings",
    // Why different
    // diffKicker: "The DocuArena Advantage",
    diffTitle: "Why DocuArena Is Different",
    diffHead: ["Traditional Approach", "DocuArena"],
    diff: [
      ["Spreadsheets and paper logs", "Enterprise paper Records Management Platform"],
      ["Manual record tracking", "Barcode-Verified Chain of Custody"],
      // ["Generic Document Management Software", "Purpose-Built paper Records Management"],
      // ["Manual retrieval requests", "Automated Work Order Management"],
      ["Limited warehouse visibility", "Real-Time Warehouse Operations"],
      ["Manual retention tracking", "Automated Retention Management"],
      // ["Disconnected operational tools", "One Unified Enterprise Platform"],
      // ["Limited mobility", "Mobile Warehouse Operations"],
      ["Static reporting", "Live Executive Dashboards"],
      ["Stand-alone applications", "Enterprise API Integration"],
    ],
    // Experts
    // expertsKicker: "Built by the People Who Manage Records",
    expertsTitle: "Built by Records Management Experts",
    expertsP2:
      "Docuarena was designed by professionals with decades of practical experience in records management, warehouse operations, and enterprise information governance.",
    expertsP3:
      "When you choose DocuArena, You're partnering with specialists who understand both the technology and the day-to-day realities of paper Records Management.",
    // Training
    // trainingKicker: "Knowledge Transfer",
    trainingTitle: "Knowledge Transfer That Ensures Success",
    trainingP1: "Successful implementations depend on knowledgeable users.",
    // trainingP2: "Our structured knowledge transfer programs are delivered directly by the team behind DocuArena and include:",
    training: [
      "Warehouse Operators",
      "Records Officers",
      "Customer Service Teams",
      "System Administrators",
      "Supervisors",
      "Management Teams",
    ],
    trainingP3:
      "Our Train-the-Trainer methodology combines classroom learning with practical, hands-on operational training.",
    trainingCta: "Contact Our Team",
    // Journey
    // journeyKicker: "Your Journey with DocuArena",
    journeyTitle: "Your Journey with DocuArena",
    journeySub: "Our relationship begins long before implementation — and continues long after go-live.",
    journey: [
      { title: "Discover", desc: "Understand your business objectives and operational challenges." },
      { title: "Assess", desc: "Analyze your current warehouse operations and records management processes." },
      { title: "Configure", desc: "Configure DocuArena to match your operational model." },
      { title: "Implement", desc: "Deploy the platform and prepare your operational environment." },
      { title: "Train", desc: "Transfer knowledge and prepare your teams for success." },
      { title: "Go Live", desc: "Support your production rollout and operational stabilization." },
      { title: "Continuous Improvement", desc: "Provide ongoing support, enhancements, and future innovation." },
    ],
    // Final CTA
finalTitle: "Ready to update your paper document management processes?",
    finalP1:
      "Whether you manage a single archive room or multiple records centers across different locations, DocuArena provides the visibility, accountability, and operational excellence needed to govern every paper record throughout its lifecycle.",
    finalP2: "Take the next step toward a more efficient, compliant, and intelligent records management operation.",
    finalP3: "Schedule Your Personalized Demonstration Today",
    finalCta1: "Book a Live Demo",
    finalCta2: "Calculate Your Savings",
    finalCta3: "Contact a Solution Specialist",
    // Footer callout
    calloutLine: "Purpose-Built for paper Records Management.",
    calloutLine2: "Designed for Enterprise Operations.",
    calloutLine3: "Built for Complete Control.",
  },
  fr: {
    heroBadge: "Gestion des documents papier",
    heroTitle:     "Prenez le contrôle total de vos documents papier",
    heroSub: "Gestion documentaire et entrepôt de niveau entreprise",
    // heroPain: "Fichiers perdus. Récupérations lentes. Absence de preuve de garde. Coûts d'entrepôt croissants.",
    heroDesc:"DocuArena est une plateforme de gestion des documents papier (PRM) spécialement conçue pour offrir à votre organisation une visibilité et un contrôle complets sur chaque document papier, de sa réception à sa destruction sécurisée.",
    // heroDesc2:
      // "Conçue spécifiquement pour les organisations gérant des archives papier, DocuArena transforme les opérations manuelles d'entrepôt en flux de travail intelligents pilotés par code-barres qui améliorent l'efficacité opérationnelle, renforcent la conformité et réduisent les coûts.",
    heroCta: "Réserver une démo en direct",
    heroCtaAlt: "Calculer vos économies",
    readyTitle: "Prêt pour l'entreprise",
    ready: [
      "Chaîne de garde vérifiée par code-barres",
      "Piste d'audit complète",
      "Sécurité basée sur les rôles",
      "Multilingue (English • العربية • Français)",
      "Intégration API REST",
      "Évolutivité d'entreprise",
      "Gestion sécurisée du cycle de vie des documents papier",
    ],
    // challengesKicker: "La réalité de la gestion manuelle des documents",
    challengesTitle: "Ces défis vous semblent-ils familiers ?",
    challengesSub: "Gérer des documents papier ne devrait pas signifier gérer l'incertitude.",
    challenges: [
      "Des fichiers disparaissent sans que personne ne sache où ils sont.",
      "Les demandes de récupération prennent des heures — voire des jours.",
      "Les audits deviennent stressants car les documents ne peuvent pas être entièrement tracés.",
      "L'espace d'entrepôt continue de croître sans visibilité.",
      "Les feuilles de calcul manuelles créent des erreurs et des doublons.",
      "Les documents circulent sans preuve de garde documentée.",
      "Les équipes travaillent dans des systèmes déconnectés.",
      "La direction manque de visibilité opérationnelle en temps réel.",
    ],
    challengesClose:
      "Si l'un de ces points vous semble familier, vous n'êtes pas seul. Ce sont exactement les défis que DocuArena a été conçu pour résoudre.",
    // matterKicker: "Pourquoi les documents papier comptent toujours",
    matterTitle: "Les documents papier comptent toujours",
    matterP1:
      "La transformation numérique a changé la façon dont les organisations gèrent l'information — mais elle n'a pas éliminé les documents papier.",
    matterP2:
      "Contrats originaux, dossiers juridiques, documents financiers, dossiers de santé, plans d'ingénierie et archives gouvernementales exigent toujours un stockage papier sécurisé et une manipulation contrôlée.",
    matterP3:
      "Pourtant, de nombreuses organisations continuent de gérer ces actifs critiques avec des feuilles de calcul, des registres papier et des processus manuels. Le résultat est prévisible :",
    matter: [
      "Fichiers perdus",
      "Récupération lente",
      "Exposition à la non-conformité",
      "Inefficacité opérationnelle",
      "Coûts d'entrepôt croissants",
      "Visibilité limitée",
    ],
    matterClose : " DocuArena a été spécialement conçu pour relever ces défis grâce à une gestion intelligente des documents papier basée sur les codes-barres." ,    // platformKicker: "Une seule plateforme.",
    platformTitle: "Une seule plateforme",
    platform: [
      { q: "Impossible de trouver un fichier ?", a: "La recherche avancée localise toute boîte, tout fichier ou tout document en quelques secondes." },
      { q: "Demandes de récupération noyées dans les e-mails ?", a: "Les bons de travail automatisés gèrent tout le cycle de vie de la demande — de l'approbation à la livraison." },
      { q: "Aucune visibilité sur les opérations d'entrepôt ?", a: "Le suivi d'entrepôt en direct vous donne un contrôle complet sur les emplacements, l'occupation et les mouvements." },
      { q: "Des documents partent sans responsabilité ?", a: "Chaque mouvement est vérifié par scan de code-barres, créant une chaîne de garde numérique complète." },
      { q: "Des équipes travaillant sur plusieurs sites ?", a: "L'application mobile garde opérateurs, chauffeurs et équipes terrain connectés en temps réel." },
      // { q: "Les échéances de conservation approchent ?", a: "Les calendriers de conservation automatisés et les alertes de destruction garantissent une gestion conforme des documents." },
      { q: "Des problèmes opérationnels découverts trop tard ?", a: "La gestion des exceptions identifie les problèmes avant qu'ils ne deviennent des violations de SLA." },
      { q: "La direction manque de visibilité ?", a: "Les tableaux de bord exécutifs fournissent KPI en direct, utilisation de l'entrepôt, performance et activité client." },
      { q: "Un DMS ou ERP déjà en place ?", a: "DocuArena s'intègre en toute fluidité à vos systèmes existants via des API REST — sans perturber vos investissements technologiques actuels." },
    ],
    platformClose: "Une seule plateforme d'entreprise. Un contrôle opérationnel complet.",
    // lifecycleKicker: "Le cycle de vie documentaire",
    lifecycleTitle: "De la réception à la destruction sécurisée",
    lifecycleSub: "Chaque document papier suit un cycle de vie entièrement contrôlé.",
    lifecycle: [
      { title: "Réception", desc: "Les documents sont reçus, enregistrés et validés." },
      { title: "Attribution du code-barres", desc: "Chaque boîte, fichier et document reçoit une identité unique." },
      { title: "Stockage", desc: "Les documents sont intelligemment assignés à des emplacements d'entrepôt optimisés." },
      { title: "Gestion des demandes", desc: "Les utilisateurs autorisés soumettent des demandes de récupération et de service." },
      { title: "Récupération et livraison", desc: "Les équipes d'entrepôt et de transport exécutent des bons de travail vérifiés par code-barres." },
      { title: "Retour", desc: "Les documents retournés sont scannés et restaurés automatiquement à leur emplacement." },
      { title: "Gestion de la conservation", desc: "Les calendriers de conservation sont surveillés avec des notifications automatisées." },
      { title: "Destruction sécurisée", desc: "Les documents expirés sont détruits via des processus contrôlés, documentés et entièrement audités." },
    ],
    // featuresKicker: "Capacités de la plateforme",
    featuresTitle: "Tout ce dont vous avez besoin dans une seule plateforme d'entreprise",
    featuresSub: "Des modules puissants et spécialisés qui fonctionnent ensemble comme un système unifié.",
    features: [
      { title: "Gestion intelligente de l'entrepôt", desc: "Gérez entrepôts, structures de stockage, types de supports et capacité depuis une plateforme centralisée." },
      { title: "Gestion des code-barres", desc: "Générez, imprimez et réimprimez des code-barres pour entrepôts, emplacements, boîtes, fichiers et documents." },
      { title: "Recherche avancée", desc: "Localisez instantanément les documents par code-barres, descriptions, métadonnées, départements, clients, dates ou critères personnalisés." },
      { title: "Gestion des bons de travail", desc: "Automatisez récupérations, retours, transports, demandes de destruction et services internes." },
      { title: "Opérations mobiles", desc: "Permettez aux opérateurs d'exécuter bons de travail et scans de code-barres partout via des appareils portables." },
      { title: "Gestion de flotte", desc: "Coordonnez véhicules, chauffeurs, coursiers et livraisons avec une visibilité opérationnelle complète." },
      { title: "Gestion de la conservation", desc: "Gérez automatiquement les calendriers légaux, dates de révision et workflows de destruction sécurisée." },
      { title: "Gestion des exceptions", desc: "Surveillez les problèmes opérationnels et les exceptions SLA avant qu'ils n'affectent le service client." },
      { title: "Tableaux de bord et reporting", desc: "Mesurez l'utilisation de l'entrepôt, l'activité client, les KPI, la productivité et la performance via des tableaux en temps réel." },
      { title: "Administration d'entreprise", desc: "Gérez utilisateurs, rôles, permissions, départements, clients, contrats et règles métier depuis une console sécurisée." },
    ],
    mobileHeroTitle: "DocuArena Mobile",
    mobileHeroSub: "Chaque opération dans votre poche",
    mobileHeroDesc:
      "Le personnel d'entrepôt et les équipes terrain restent connectés à la plateforme centrale où qu'ils soient. Scannez, exécutez, vérifiez et mettez à jour les documents papier en temps réel — sans paperasse, sans délai.",
    // mobileKicker: "Opérations partout",
    mobileTitle: "Opérations partout",
    mobileSub: "Les opérations d'entrepôt ne doivent jamais s'arrêter parce que votre équipe quitte le bureau , L'application mobile DocuArena permet au personnel d'entrepôt d'effectuer toutes leurs tâches où et quand ils le souhaitent ; chaque action reste visible et enregistrée.",
    mobileDesc: "L'application mobile DocuArena permet au personnel d'entrepôt et aux équipes terrain de :",
    mobile: [
      "Scanner les code-barres instantanément",
      "Exécuter les bons de travail",
      "Mettre à jour le statut des documents en temps réel",
      "Vérifier livraisons et retours",
      "Capturer les activités d'entrepôt",
      "Synchroniser chaque opération avec la plateforme centrale",
    ],
    mobileClose: "Dans l'entrepôt ou chez un client, chaque mouvement reste visible et entièrement contrôlé.",
    mobileCta: "Découvrir l'expérience mobile",
    // costKicker: "Le coût caché des processus manuels",
    costTitle: "Combien vous coûtent réellement les processus manuels ?",
    costSub:
      "Chaque récupération retardée. Chaque fichier égaré. Chaque visite inutile à l'entrepôt. Chaque feuille de calcul. Chaque problème de conformité. Tous ont un coût mesurable.",
    costDesc: "Utilisez notre calculateur interactif de coûts de gestion des documents papier pour découvrir :",
    cost: [
      "Les coûts opérationnels actuels",
      "L'efficacité de l'entrepôt",
      "L'utilisation de la main-d'œuvre",
      "La performance de récupération",
      "Les économies annuelles potentielles",
      "Le retour sur investissement (ROI) attendu",
      "La période de remboursement estimée",
    ],
    costCta: "Calculer vos économies",
    // diffKicker: "L'avantage DocuArena",
    diffTitle: "Pourquoi DocuArena est différent",
    diffHead: ["Approche traditionnelle", "DocuArena"],
    diff: [
      ["Feuilles de calcul et registres papier", "Plateforme d'entreprise de gestion des documents papier"],
      ["Suivi manuel des documents", "Chaîne de garde vérifiée par code-barres"],
      // ["Logiciel générique de gestion documentaire", "Gestion des documents papier sur mesure"],
      // ["Demandes de récupération manuelles", "Gestion automatisée des bons de travail"],
      ["Visibilité d'entrepôt limitée", "Opérations d'entrepôt en temps réel"],
      ["Conservation manuelle", "Gestion automatisée de la conservation"],
      // ["Outils opérationnels déconnectés", "Une plateforme d'entreprise unifiée"],
      // ["Mobilité limitée", "Opérations d'entrepôt mobiles"],
      ["Reporting statique", "Tableaux de bord exécutifs en direct"],
      ["Applications autonomes", "Intégration API d'entreprise"],
    ],
    // expertsKicker: "Créé par ceux qui gèrent les documents",
    expertsTitle: "Créé par des experts en gestion des documents",
    // expertsP1: "DocuArena n'a pas été développé comme un logiciel générique.",
    expertsP2:"DocuArena a été conçu par des professionnels cumulant des décennies d'expérience pratique en gestion d'archives, en exploitation d'entrepôts et en gouvernance de l'information d'entreprise.",
    expertsP3:"En choisissant DocuArena, vous collaborez avec des spécialistes qui maîtrisent à la fois la technologie et les réalités quotidiennes de la gestion des archives papier.",
    // expertsP4: "Choisir DocuArena, ce n'est pas simplement acheter un logiciel.",
    // expertsP5:
      // "C'est s'associer à des spécialistes qui comprennent à la fois la technologie et les réalités quotidiennes de la gestion des documents papier.",
    // trainingKicker: "Transfert de connaissances",
    trainingTitle: "Un transfert de connaissances qui garantit le succès",
    trainingP1: "Des implémentations réussies reposent sur des utilisateurs compétents.",
    // trainingP2: "Nos programmes structurés de transfert de connaissances sont délivrés par l'équipe derrière DocuArena :",
    training: [
      "Opérateurs d'entrepôt",
      "Responsables des documents",
      "Équipes de service client",
      "Administrateurs système",
      "Superviseurs",
      "Équipes de direction",
    ],
    trainingP3:
      "Notre méthodologie Train-the-Trainer combine apprentissage en classe et formation pratique opérationnelle.",
    trainingCta: "Contacter notre équipe",
    // journeyKicker: "Votre parcours avec DocuArena",
    journeyTitle: "Votre parcours avec DocuArena",
    journeySub: "Notre relation commence bien avant l'implémentation — et se poursuit bien après la mise en service.",
    journey: [
      { title: "Découverte", desc: "Comprendre vos objectifs métier et défis opérationnels." },
      { title: "Évaluation", desc: "Analyser vos opérations d'entrepôt et processus de gestion actuels." },
      { title: "Configuration", desc: "Configurer DocuArena selon votre modèle opérationnel." },
      { title: "Implémentation", desc: "Déployer la plateforme et préparer votre environnement." },
      { title: "Formation", desc: "Transférer les connaissances et préparer vos équipes." },
      { title: "Mise en service", desc: "Accompagner votre déploiement et la stabilisation opérationnelle." },
      { title: "Amélioration continue", desc: "Fournir support continu, améliorations et innovations futures." },
    ],
finalTitle: "Prêt à moderniser vos processus de gestion des documents papier ?",
    finalP1:
      "Que vous gériez une seule salle d'archives ou plusieurs centres de documents sur différents sites, DocuArena offre la visibilité, la responsabilité et l'excellence opérationnelle nécessaires pour gouverner chaque document papier tout au long de son cycle de vie.",
    finalP2: "Faites le prochain pas vers une gestion documentaire plus efficace, conforme et intelligente.",
    finalP3: "Planifiez votre démonstration personnalisée dès aujourd'hui",
    finalCta1: "Réserver une démo en direct",
    finalCta2: "Calculer vos économies",
    finalCta3: "Contacter un spécialiste",
    calloutLine: "Conçu sur mesure pour la gestion des documents papier.",
    calloutLine2: "Conçu pour les opérations d'entreprise.",
    calloutLine3: "Construit pour un contrôle complet.",
  },
  ar: {
    heroBadge: "إدارة المستندات الورقية",
    heroTitle: "تحكم بشكل كامل على مستنداتك الورقية",
    heroSub: "إدارة المستندات والمخازن على مستوى المؤسسات",
    // heroPain: "ملفات ضائعة. استرجاع بطيء. لا إثبات للحفظ. تكاليف مخازن متزايدة.",
    heroDesc:"DocuArena هي منصة مصممة خصيصًا لإدارة السجلات الورقيه (PRM) تمنح مؤسستك رؤية كاملة وتحكمًا تامًا في كل سجل ورقي - من الاستلام إلى التدمير الآمن.",
    // heroDesc2:
      // "مبنية خصيصاً للمؤسسات التي تدير أرشيفات فعلية، تحوّل DocuArena عمليات المخزن اليدوية إلى سير عمل ذكية تعتمد على الباركود، لتحسين الكفاءة التشغيلية وتقوية الالتزام وخفض التكاليف.",
    heroCta: "احجز عرضاً",
    heroCtaAlt: "احسب مدخراتك",
    readyTitle: "جاهزة للمؤسسات",
    ready: [
      "سلسلة حفظ مُتحقق منها بالباركود",
      "سجل تدقيق كامل",
      "أمان قائم على الأدوار",
      "متعددة اللغات (English • العربية • Français)",
      "تكامل API",
      "قابلية توسع مؤسسية",
      "إدارة آمنة لدورة حياة المستندات الورقية",
    ],
    // challengesKicker: "واقع إدارة المستندات اليدوية",
    challengesTitle: "هل هذه التحديات مألوفة لديكم؟",
    challengesSub: "إدارة المستندات الورقية لا يجب أن تعني إدارة حالة من عدم اليقين.",
    challenges: [
      "ملفات تختفي ولا يعرف أحد أين ذهبت.",
      "طلبات الاسترجاع تستغرق ساعات — أو حتى أياماً.",
      "المراجعات تصبح مرهقة لأن المستندات لا يمكن تتبعها بالكامل.",
      "مساحة المخزن تستمر في النمو دون رؤية واضحة.",
      "الجداول اليدوية تخلق أخطاء وعملاً مكرراً.",
      "المستندات تنتقل دون إثبات موثق للحفظ.",
      "الفرق تعمل في أنظمة منفصلة.",
      "الإدارة تفتقر إلى رؤية تشغيلية لحظية.",
    ],
    challengesClose: "إذا كان أي من هذه النقاط مألوفاً لديكم، فأنتم لستم وحدكم. هذه هي بالضبط التحديات التي بُني DocuArena لحلها.",
    // matterKicker: "لماذا تظل المستندات الورقية مهمة",
    matterTitle: "المستندات الورقية لا تزال مهمة",
    matterP1: "غيّر التحول الرقمي طريقة إدارة المؤسسات للمعلومات — لكنه لم يلغِ المستندات الورقية.",
    matterP2:
      "العقود الأصلية والملفات القانونية والمستندات المالية والملفات الصحية والمخططات الهندسية والأرشيفات الحكومية لا تزال تتطلب تخزيناً  آمناً وتداولاً مُتحكماً فيه.",
    matterP3:
      "ومع ذلك تواصل مؤسسات كثيرة إدارة هذه الأصول الحرجة عبر الجداول اليدوية والسجلات الورقية. والنتيجة متوقعة:",
    matter: [
      "ملفات ضائعة",
      "استرجاع بطيء",
      "تعرض للامتثال",
      "عدم كفاءة تشغيلية",
      "تكاليف مخازن متزايدة",
      "رؤية محدودة",
    ],
    matterClose: "بُني DocuArena خصيصاً لحل هذه التحديات عبر إدارة ذكية للمستندات الورقية تعتمد على الباركود.",
    // platformKicker: "منصة واحدة.",
    platformTitle: "منصة واحدة",
    platform: [
      { q: "لا يمكنك العثور على ملف؟", a: "البحث المتقدم يحدد موقع أي صندوق أو ملف أو مستند في ثوانٍ." },
      { q: "طلبات الاسترجاع غارقة في الإيميلات؟", a: "أوامر العمل الآلية تدير دورة الطلب كاملة — من الاعتماد حتى التسليم." },
      { q: "لا رؤية لعمليات المخزن؟", a: "المراقبة الحية للمخزن تمنحك تحكماً كاملاً في مواقع التخزين والإشغال والحركة." },
      { q: "مستندات تغادر دون مساءلة؟", a: "كل حركة تُتحقق عبر مسح الباركود، فتُنشأ سلسلة حفظ رقمية كاملة." },
      { q: "فرق تعمل عبر مواقع متعددة؟", a: "التطبيق المحمول يبقي مشغلي المخزن والسائقين والفرق الميدانية متصلين لحظياً." },
      // { q: "مواعيد الاحتفاظ تقترب؟", a: "جداول الاحتفاظ الآلية وتنبيهات الإتلاف تضمن إدارة المستندات وفق السياسة." },
      { q: "مشاكل تشغيلية تُكتشف متأخراً؟", a: "إدارة الاستثناءات تحدد المشاكل قبل أن تتحول إلى مخالفات لاتفاقيات الخدمة." },
      { q: "الإدارة تفتقر إلى رؤية تشغيلية؟", a: "لوحات القيادة التنفيذية توفر مؤشرات حية وإشغال المخزن والأداء ونشاط العملاء." },
      { q: "لديكم بالفعل DMS أو ERP؟", a: "يتكامل DocuArena بسلاسة مع أنظمتكم الحالية عبر REST API — دون تعطيل استثماراتكم التقنية." },
    ],
    platformClose: "منصة مؤسسية واحدة. تحكم تشغيلي كامل.",
    // lifecycleKicker: "دورة حياة المستند",
    lifecycleTitle: "من الاستلام حتى الإتلاف الآمن",
    lifecycleSub: "كل مستند ورقي يتبع دورة حياة مُتحكماً فيها بالكامل.",
    lifecycle: [
      { title: "الاستلام", desc: "تُستلم المستندات وتُسجل وتُتحقق." },
      { title: "إسناد الباركود", desc: "كل صندوق وملف ومستند يحصل على هوية فريدة." },
      { title: "التخزين", desc: "تُسند المستندات بذكاء إلى مواقع تخزين مثالية في المخزن." },
      { title: "إدارة الطلبات", desc: "المستخدمون المصرح لهم يقدمون طلبات الاسترجاع والخدمة." },
      { title: "الاسترجاع والتسليم", desc: "فرق المخزن والنقل تنفذ أوامر عمل مُتحققاً منها بالباركود." },
      { title: "الإعادة", desc: "تُمسح المستندات المُعادة وتُرجع تلقائياً إلى مواقعها." },
      { title: "إدارة الاحتفاظ", desc: "تُراقب جداول الاحتفاظ مع إشعارات آلية." },
      { title: "الإتلاف الآمن", desc: "تُتلف المستندات منتهية الصلاحية عبر عمليات مُتحكم فيها وموثقة وقابلة للتدقيق بالكامل." },
    ],
    // featuresKicker: "قدرات المنصة",
    featuresTitle: "كل ما تحتاجه في منصة مؤسسية واحدة",
    featuresSub: "وحدات قوية ومتخصصة تعمل معاً كنظام واحد موحد.",
    features: [
      { title: "إدارة المخازن الذكية", desc: "إدارة المخازن وهياكل التخزين وأنواع الوسائط والسعة من منصة مركزية واحدة." },
      { title: "إدارة الباركود", desc: "إنشاء وطباعة وإعادة طباعة الباركود للمخازن والمواقع والصناديق والملفات والمستندات." },
      { title: "البحث المتقدم", desc: "تحديد موقع المستندات فوراً بالباركود أو الوصف أو البيانات الوصفية أو الأقسام أو العملاء أو التواريخ." },
      { title: "إدارة أوامر العمل", desc: "أتمتة الاسترجاع والإعادة والنقل وطلبات الإتلاف والخدمات الداخلية للمخزن." },
      { title: "العمليات المحمولة", desc: "تمكين مشغلي المخزن من تنفيذ أوامر العمل ومسح الباركود في أي مكان عبر الأجهزة المحمولة." },
      { title: "إدارة الأسطول", desc: "تنسيق المركبات والسائقين والمناديب والتسليمات مع رؤية تشغيلية كاملة." },
      { title: "إدارة الاحتفاظ", desc: "إدارة جداول الاحتفاظ القانونية وتواريخ المراجعة وسير عمل الإتلاف الآمن تلقائياً." },
      { title: "إدارة الاستثناءات", desc: "مراقبة المشاكل التشغيلية واستثناءات اتفاقيات الخدمة قبل أن تؤثر على خدمة العملاء." },
      { title: "لوحات القيادة والتقارير", desc: "قياس إشغال المخزن ونشاط العملاء والمؤشرات التشغيلية والإنتاجية والأداء عبر لوحات لحظية." },
      { title: "إدارة المؤسسة", desc: "إدارة المستخدمين والأدوار والصلاحيات والأقسام والعملاء والعقود وقواعد العمل من وحدة إدارة آمنة." },
    ],
    mobileHeroTitle: "DocuArena Mobile",
    mobileHeroSub: "كل عملية في جيبك",
    mobileHeroDesc:
      "طاقم المخزن والفرق الميدانية يبقون متصلين بالمنصة المركزية من أي مكان. امسح، نفّذ، تحقق وحدّث حالة الوثائق في الوقت الفعلي — بدون أوراق وبدون تأخير.",
    // mobileKicker: "عمليات في أي مكان",
    mobileTitle: "عمليات في أي مكان",
    mobileSub: "عمليات المخزن لا يجب أن تتوقف لمجرد أن فريقك يغادر المكتب , يتيح تطبيق DocuArena للهواتف المحمولة لموظفي المستودعات أداء جميع المهام أينما كانوا ومتى ما كانوا، ويبقى كل إجراء مرئيًا ومسجلاً.",
    mobileDesc: "تطبيق DocuArena المحمول يمكن طاقم المخزن والفرق الميدانية من:",
    mobile: [
      "مسح الباركود فوراً",
      "تنفيذ أوامر العمل",
      "تحديث حالة المستند لحظياً",
      "التحقق من التسليمات والإعادة",
      "توثيق أنشطة المخزن",
      "مزامنة كل عملية مع المنصة المركزية",
    ],
    mobileClose: "داخل المخزن أو في موقع العميل، تظل كل حركة مرئية ومُتحكماً فيها بالكامل.",
    mobileCta: "اكتشف التجربة المحمولة",
    // costKicker: "التكلفة الخفية للعمليات اليدوية",
    costTitle: "كم تكلفك العمليات اليدوية  ؟",
    costSub:
      "كل استرجاع متأخر. كل ملف في غير مكانه. كل زيارة مخزن غير ضرورية. كل جدول يدوي. كل مشكلة امتثال. جميعها لها تكلفة قابلة للقياس.",
    costDesc: "استخدم حاسبة تكاليف إدارة المستندات الورقية التفاعلية لدينا لاكتشاف:",
    cost: [
      "التكاليف التشغيلية الحالية",
      "كفاءة المخزن",
      "استغلال العمالة",
      "أداء الاسترجاع",
      "الوفورات السنوية المحتملة",
      "العائد المتوقع على الاستثمار (ROI)",
      "فترة استرداد التكلفة المقدرة",
    ],
    costCta: "احسب مدخراتك",
    // diffKicker: "ميزة DocuArena",
    diffTitle: "لماذا يختلف DocuArena",
    diffHead: ["النهج التقليدي", "DocuArena"],
    diff: [
      ["جداول وسجلات ورقية", "منصة مؤسسية لإدارة المستندات الورقية"],
      ["تتبع يدوي للمستندات", "سلسلة حفظ مُتحقق منها بالباركود"],
      // ["برامج إدارة مستندات عامة", "إدارة مستندات ورقية مصممة خصيصاً"],
      // ["طلبات استرجاع يدوية", "إدارة آلية لأوامر العمل"],
      ["رؤية مخزن محدودة", "عمليات مخزن لحظية"],
      ["احتفاظ يدوي", "إدارة آلية للاحتفاظ"],
      // ["أدوات تشغيلية منفصلة", "منصة مؤسسية موحدة واحدة"],
      // ["تنقل محدود", "عمليات مخزن محمولة"],
      ["تقارير ثابتة", "لوحات قيادة تنفيذية حية"],
      ["تطبيقات منعزلة", "تكامل API مؤسسي"],
    ],
    // expertsKicker: "بناها من يديرون المستندات",
    expertsTitle: "بناها خبراء إدارة المستندات",
    // expertsP1: "لم يُطوَّر DocuArena كبرنامج عام.",
    expertsP2:"صُمم DocuArena على يد متخصصين يتمتعون بعقود من الخبرة العملية في إدارة السجلات، وعمليات المستودعات، وحوكمة معلومات المؤسسات.",
    expertsP3:"باختيارك DocuArena، فإنك تتعاون مع متخصصين يفهمون التكنولوجيا والواقع العملي لإدارة السجلات الورقية.",
    // expertsP4: "عندما تختار DocuArena، فأنت لا تشتري برنامجاً فحسب.",
    // expertsP5: "أنت تشراك مع متخصصين يفهمون التقنية وواقع العمل اليومي لإدارة المستندات الورقية.",
    // trainingKicker: "نقل المعرفة",
    trainingTitle: "نقل معرفة يضمن النجاح",
    trainingP1: "التطبيقات الناجحة تعتمد على مستخدمين متمكنين.",
    // trainingP2: "برامج نقل المعرفة المنظمة لدينا تُقدَّم مباشرة من فريق DocuArena وتشمل:",
    training: [
      "مشغلي المخازن",
      "مسؤولي المستندات",
      "فرق خدمة العملاء",
      "مسؤولي الأنظمة",
      "المشرفين",
      "فرق الإدارة",
    ],
    trainingP3: "منهجية تدريب المدربين لدينا تجمع بين التعلم النظري والتدريب العملي التشغيلي الميداني.",
    trainingCta: "تواصل مع فريقنا",
    // journeyKicker: "رحلتك مع DocuArena",
    journeyTitle: "رحلتك مع DocuArena",
    journeySub: "علاقتنا تبدأ قبل التنفيذ بوقت طويل — وتستمر بعد التشغيل .",
    journey: [
      { title: "الاكتشاف", desc: "فهم أهدافك التجارية والتحديات التشغيلية." },
      { title: "التقييم", desc: "تحليل عمليات المخزن الحالية وعمليات إدارة المستندات." },
      { title: "الإعداد", desc: "تهيئة DocuArena ليطابق نموذجك التشغيلي." },
      { title: "التنفيذ", desc: "نشر المنصة وتجهيز بيئتك التشغيلية." },
      { title: "التدريب", desc: "نقل المعرفة وإعداد فرقك للنجاح." },
      { title: "التشغيل", desc: "دعم انطلاق الإنتاج واستقرار العمليات." },
      { title: "التحسين المستمر", desc: "توفير دعم مستمر وتحسينات وابتكارات مستقبلية." },
    ],
    finalTitle: "جاهز لتحديث عمليات إدارة مستنداتك الورقية ؟",
    finalP1:
      "سواء كنت تدير غرفة أرشيف واحدة أو مراكز مستندات متعددة عبر مواقع مختلفة، يوفر DocuArena الرؤية والمساءلة والتميز التشغيلي اللازم لحوكمة كل مستند ورقي طوال دورة حياته.",
    finalP2: "اتخذ الخطوة التالية نحو إدارة مستندات أكثر كفاءة والزاماً وذكاءً.",
    finalP3: "احجز عرضك التوضيحي المخصص اليوم",
    finalCta1: "احجز عرضاً حياً",
    finalCta2: "احسب مدخراتك",
    finalCta3: "تواصل مع مختص",
    calloutLine: "مصمم خصيصاً لإدارة المستندات الورقية.",
    calloutLine2: "مصمم لعمليات المؤسسات.",
    calloutLine3: "مبني للتحكم الكامل.",
  },
};

export function getDocuarenaContent(lang) {
  return C[lang] || C.en;
}
